name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-macos-arm64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      shell: bash
      run: |
        git clone https://github.com/fltk/fltk --depth=1
        cd fltk
        cmake -Bbin -S. -DCMAKE_SYSTEM_NAME=Macos -DCMAKE_OSX_ARCHITECTURES=arm64 -DFLTK_BUILD_EXAMPLES=ON -DFLTK_BUILD_FLUID=OFF -DFLTK_BUILD_TEST=OFF -DFLTK_BUILD_FLTK_OPTIONS=OFF && cmake --build bin --parallel
